### ISSUE TITLE
Install gulp globally

### ISSUE THREAD

**Issue by Mteixeira88** [andreros/typescript-boilerplate#2]
# Typescript Boilerplate

Boilerplate for a Typescript project with SASS for CSS and Handlebars for HTML templating.

## Expected Behavior

Gulp Edition uses Node for core processing, npm to manage project dependencies, and gulp.js to run tasks and interface with the core library. Node version 8 or higher suffices. You can follow the directions for installing Node on the Node website if you haven't done so already. Installation of Node will include npm.

It's also highly recommended that you install gulp globally.

## Actual Behavior
Don't have any mention to install gulp globaly

**Comment by andreros** [comment]
Thank you for your contribution @Mteixeira88. I will be also including the reference to https://github.com/gulpjs/gulp/blob/4.0/docs/getting-started.md in the README.md file and documentation, as you suggested.
